name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DigitalOcean Docker Registry
      - name: Log in to DigitalOcean Docker Registry
        run: echo "${{ secrets.DIGITALOCEAN_API_TOKEN }}" | docker login registry.digitalocean.com -u do --password-stdin

      # Step 4: Build and Push Docker image to DigitalOcean Registry
      - name: Build and Push Docker Image
        run: |
          docker pull bitnami/laravel:latest
          docker tag bitnami/laravel:latest registry.digitalocean.com/linktic-registry/linktic-api:latest
          docker push registry.digitalocean.com/linktic-registry/linktic-api:latest

      # Step 5: SSH into DigitalOcean Droplet and Deploy the Image
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Autenticar con Docker Registry
            echo "${{ secrets.DIGITALOCEAN_API_TOKEN }}" | docker login registry.digitalocean.com -u do --password-stdin

            # Descargar la última imagen desde el Registry
            docker pull registry.digitalocean.com/linktic-registry/linktic-api:latest

            # Ejecutar el contenedor desde la imagen
            docker run -d --name linktic-api -p 8080:8000 \
              -e DB_HOST=linktic-db \
              -e DB_PORT=3306 \
              -e DB_DATABASE=linkticdb \
              -e DB_USERNAME=linkticuser \
              -e DB_PASSWORD=secret \
              registry.digitalocean.com/linktic-registry/linktic-api:latest
