name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Docker Registry
        run: echo "${{ secrets.DIGITALOCEAN_API_TOKEN }}" | docker login registry.digitalocean.com -u do --password-stdin

      - name: Build and Push with docker-compose
        run: |
          docker compose -f docker-compose.yml build
          docker tag bitnami/laravel:latest registry.digitalocean.com/linktic-registry/linktic-api:latest
          docker push registry.digitalocean.com/linktic-registry/linktic-api:latest

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull registry.digitalocean.com/linktic-registry/linktic-api:latest
            docker-compose down
            docker-compose up -d
