name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Ajusta a tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to DigitalOcean Docker Registry
      - name: Log in to DigitalOcean Docker Registry
        run: echo "${{ secrets.DIGITALOCEAN_API_TOKEN }}" | docker login registry.digitalocean.com -u do --password-stdin

      # Step 3: Build and push the services defined in docker-compose.yml
      - name: Build and Push Docker Images
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

      # Step 4: Deploy to DigitalOcean
      - name: Deploy to DigitalOcean
        run: echo "Deploy step here"
